# Generated by Django 4.2 on 2024-09-08 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CpInputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_jumlah', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=False)),
                ('mp_pos', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=False)),
                ('material_jumlah', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=False)),
                ('material_std', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=False)),
                ('mesin_normal', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=False)),
                ('metode_sesuai', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=False)),
                ('plan_vs_actual', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=False)),
                ('environment_aman', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=False)),
                ('tanggal_check', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
