# Generated by Django 4.2 on 2024-09-10 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CheckPointApp', '0002_areamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpinputmodel',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CheckPointApp.areamodel'),
            preserve_default=False,
        ),
    ]
